### ISSUE TITLE
Proposal: watch markdown content

### ISSUE THREAD

**Issue by trev-dev** [aMOPel/nim-karax-website#2]
It currently looks like karun only watches the website.nim file.  The workflow could improve by watching markdown content as well

**Comment by aMOPel** [comment]
Did you actually test that? From what I understand it watches all files in the directory it was started in. That is actually the reason I put all the things into the `nim` folder. Since it would rebuild every time I would update my session file for vim and that happens even when you just change the window.

**Comment by trev-dev** [comment]
I did the following;

1.  Installed dependencies
2. Ran ./bin/transpileMarkdown && ./nimbledeps/bin/karun -r -w ./src/website.nim
3. Ran npx tailwindcss -i ./assets/prestyles.css -o ./assets/styles.css --watch
4. Made changes to website.nim, observed a hot reload.
5. Added content/momo.md
6. Navigated to /#/momo, page did not show body content
7. Ran ./bin/transpileMarkdown && nim js --out:./app.js ./src/website.nim, did not observe a hot reload
8. Manually refreshed the browser tab and saw the body content update
9. Edited and saved /content/momo.md, did not observe a hot reload

**Comment by trev-dev** [comment]
More on this, it looks like the websocket receives a refresh event, it looks like nim is rebuilding when I modify and save the page but the content on the page doesn't change.  If I reload the page, the changes do not appear.

Then I run transpileMarkdown, manually reload the page and the markup changes appear.  Using firefox 109

**Comment by trev-dev** [comment]
Could reproduce this issue in brave as well :)

**Comment by aMOPel** [comment]
Very true. Thanks for testing. The transpileMarkdown binary needs to be executed to transpile the markdown to karax DSL and that is currently not being done by the karun watcher. One would have to write another watcher or modify the karun watcher.

**Comment by aMOPel** [comment]
The karun watcher is part of the karax repo, while the transpileMarkdown is a custom script

**Comment by trev-dev** [comment]
Sounds like fun!

**Comment by trev-dev** [comment]
I think you solved this, if I am not mistaken ✔️
